config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/"). This shows an overview of all offices.
  root "offices#index"

  #############################################################################
  # NOTE: TEMPORARY DEVELOPMENT ROUTES
  # Debugging for external calls to the Open Weather Map API
  get "weather_api" => "weather_api#index"
  #############################################################################

  # Instead of "/offices/:id", allow "/:id" instead, following the root path.
  get "offices/:id" => "offices#show", as: :office

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/office.rb
class Office < ApplicationRecord
  # NOTE: Weather is already indexed using a composite key of [lat, lon, dt], don't think
  # indexing & foreign key provide much benefit here, but needs investigation
  has_many :weathers, primary_key: [:lat, :lon, :dt], query_constraints: [:lat, :lon, :dt]

  def current_weather
    Weather.current_weather(lat, lon)
  end

  def forecast
    Weather.forecast(lat, lon)
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :office, query_constraints: [:lat, :lon, :dt]

  def self.update_weather_data(lat, lon, dt)
    forecast_data = ForecastService.new.call(lat, lon, dt)

    if forecast_data
      upsert_all(forecast_data)
    end
  end

  def self.current_weather(lat, lon)
    dt = normalised_req_time
    update_weather_data(lat, lon, dt)

    find_by(lat: lat, lon: lon, dt: dt)
  end

  def self.forecast(lat, lon)
    update_weather_data(lat, lon, normalised_req_time)

    forecast_start = Time.now.utc.beginning_of_day
    forecast_end = forecast_start.advance(days: 4)

    where(lat: lat, lon: lon, dt: forecast_start...forecast_end).order(:dt)
  end

  # The data structure constructed by the service object is a list of weather
  # objects. These are for intervals of time at a specific location. Because the
  # request time is not going to be at one of those times, need to shift it
  # *down* to the last interval.
  def self.normalised_req_time
    # The forecast by default provides 8 daily records: 00:00, 03:00, 06:00,
    # 09:00, 12:00, 15:00, 18:00, and 21:00. Grab the closest one to the current time
    req_per_day = 8
    cache_interval = 24 / 8

    (0...req_per_day)
      .map { |i| DateTime.parse("00:00") + Rational(cache_interval * i, 24) }
      .min_by { |time| (DateTime.now.utc - time).abs }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def index
    @offices = Office.all
  end

  def show
    @office = Office.find(params[:id])
  end
end

app/controllers/weather_api_controller.rb
class WeatherApiController < ApplicationController
  def index
    @newcastle_weather = ForecastService.new().call(54.971250, -1.614590)
    @vancouver_weather = ForecastService.new().call(49.286610, -123.118550)
    @st_julians_weather = ForecastService.new().call(35.916160, 14.491080)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
  # A four-day forecast is provided, with [max*] 8 entries per day.
  # The data is in a flat array, ordered by date, starting with today.
  # However, the data may only exist from the current time onwards.
  def chunked_forecast_data(forecast_list)
    first_entry_dt = DateTime.parse(forecast_list[0][:dt])

    # (0...4).map
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StriveWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.fontshare.com/v2/css?f[]=general-sans@1&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offices/index.html.erb
<main class="screen">
    <% @offices.each do |office| %>
        <a class="office-link-wrapper panel-link-wrapper" href="<%= office_path(office) %>">
            <section class="panel">
                <header class="panel-header">
                    <h2 class="panel-title">
                        <%= office[:municipality] %>, <%= office[:country] %>
                    </h2>
                    <p class="panel-subtitle"><time datetime="<%= office.current_weather[:dt] %>">
                        <%= office.current_weather[:dt] %>
                    </time></p>
                </header>
                <div class="weather-summary">
                    <p class="office-weather-desc">
                        <%= office.current_weather[:name] %>
                    </p>
                    <p class="office-weather-temp">
                        <%= office.current_weather[:average_temp] %>°c
                    </p>
                </div>
                <nav class="office-panel-controls panel-controls">
                    <p class="office-panel-controls-linkto">View details --></p>
                </nav>
            </section>
        </a>
        <% end %>
</main>

app/views/offices/show.html.erb
<main class="screen">
    <section class="panel">
        <nav class="office-panel-controls panel-controls">
            <a class="office-panel-controls-linkto" href="/">&#8592; back to offices</a>
        </nav>
        <header class="panel-header">
            <h2 class="panel-title">
                <%= @office[:municipality] %>, <%= @office[:country] %>
            </h2>
            <p class="office-localtime panel-subtitle"><time datetime="<%= @office.current_weather[:dt] %>">
                    <%= @office.current_weather[:dt] %>
                </time></p>
        </header>
        <div class="panel-content weather-summary">
            <p class="office-weather-desc">
                <%= @office.current_weather[:name] %>
            </p>
            <p class="office-weather-temp">
                <%= @office.current_weather[:average_temp] %>°c
            </p>
        </div>
    </section>

    <section class="panel">
        <header class="panel-header">
            <h2 class="panel-title">Four-day forecast</h2>
        </header>
        <tab-interface>
            <% @office.forecast.in_groups_of(8).each do |forecast_days| %>
                <button slot="tab"><time datetime="<%= forecast_days[0][:dt] %>" is="relative-day">
                        <%= forecast_days[0][:dt] %>
                    </time></button>
                <div slot="tabpanel">
                    <ul role="list">
                        <% forecast_days.each do |weather| %>
                            <li>
                        <% if false %>
                                <p><time datetime="<%= weather[:dt] %>">
                                        <%= weather[:dt] %>
                                    </time></p>
                                <p><span>
                                        <%= weather[:name] %>
                                    </span>, <data>
                                        <%= weather[:average_temp] %>
                                    </data></p>
                        <% end %>
                        <%= weather.inspect %>
                            </li>
                        <% end %>
                    </ul>
                </div>
                <% end %>
        </tab-interface>
    </section>
</main>

app/views/weather_api/index.html.erb
<section style="padding-bottom: 2rem;">
  <h2>Weather in Newcastle, UK</h2>
  <p><%= @newcastle_weather[:data] %></p>
</section>
<section style="padding-bottom: 2rem;">
  <h2>Weather in Vancouver, Canada</h2>
  <p><%= @vancouver_weather[:data] %></p>
</section>
<section style="padding-bottom: 2rem;">
  <h2>Weather in S<sup>t</sup> Julian's, Malta</h2>
  <p><%= @st_julians_weather[:data] %></p>
</section>